name: Install Clang
description: Install Clang
inputs:
  architecture:
    required: true
    type: string
  al_version:
    required: true
    type: string
runs:
  using: composite
  steps:
    - run: git apply "${GITHUB_WORKSPACE}/assets/patches/clang/fix-xml2-and-zstd-lib-location.patch"
      shell: bash
      working-directory: /home/runner/src
    - run: git apply "${GITHUB_WORKSPACE}/assets/patches/clang/disable-sysroots-aarch64.patch"
      shell: bash
      working-directory: /home/runner/src
      if: ${{ inputs.architecture == 'arm64' }}
    - run: git apply "${GITHUB_WORKSPACE}/assets/patches/clang/disable-sysroots-x86.patch"
      shell: bash
      working-directory: /home/runner/src
      if: ${{ inputs.architecture == 'x86' }}
    - run: git apply "${GITHUB_WORKSPACE}/assets/patches/clang/disable-lld.patch"
      shell: bash
      working-directory: /home/runner/src
      if: ${{ inputs.al_version == 'al2' }}
    - run: ./tools/clang/scripts/build.py --without-android --without-fuchsia --use-system-cmake --host-cc /bin/clang --host-cxx /bin/clang++ --with-ml-inliner-model=''
      shell: bash
      working-directory: /home/runner/src
      if: ${{ inputs.architecture == 'arm64' }}
    - run: ./tools/clang/scripts/build.py --skip-build --without-android --without-fuchsia --with-ml-inliner-model=''
      shell: bash
      working-directory: /home/runner/src
      if: ${{ inputs.architecture == 'x86' }}
    - run: patch -p1 <"${GITHUB_WORKSPACE}/assets/patches/clang/414b7c3275b3dd71405e73f5f9ed43cfcf4421d7.patch"
      shell: bash
      working-directory: /home/runner/src/third_party/llvm
      if: ${{ inputs.al_version == 'al2' }}
    - run: ./tools/clang/scripts/build.py --skip-checkout --without-android --without-fuchsia --with-ml-inliner-model=''
      shell: bash
      working-directory: /home/runner/src
      if: ${{ inputs.architecture == 'x86' }}
